apiVersion: v1
kind: Service
metadata:
  name: ultraportal-frontend-service
  namespace: ultraportal
spec:
  selector:
    app: ultraportal-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort
  nodePort: 30081
