apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ultraportal
resources:
- namespace.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
images:
- name: paulok3tchup/ultraportal-backend
  newName: paulok3tchup/ultraportal-backend
  newTag: 18e87e8870f2ab3971817301d3e8e03f1350a70d
- name: paulok3tchup/ultraportal-frontend
  newName: paulok3tchup/ultraportal-frontend
  newTag: 18e87e8870f2ab3971817301d3e8e03f1350a70d
