apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ultraportal
resources:
- namespace.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
images:
- name: paulok3tchup/ultraportal-backend
  newName: paulok3tchup/ultraportal-backend
  newTag: 2c4b29d2f80653eb5de71139ed5223a03c2f95a2
- name: paulok3tchup/ultraportal-frontend
  newName: paulok3tchup/ultraportal-frontend
  newTag: 2c4b29d2f80653eb5de71139ed5223a03c2f95a2
