apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ultraportal
resources:
- namespace.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
images:
- name: paulok3tchup/ultraportal-backend
  newName: paulok3tchup/ultraportal-backend
  newTag: 970f3f9eec64dd0bf27221956d9953df22ee6e67
- name: paulok3tchup/ultraportal-frontend
  newName: paulok3tchup/ultraportal-frontend
  newTag: 970f3f9eec64dd0bf27221956d9953df22ee6e67
